"""Weekly report generator for AI Pulse.

Aggregates digests and trends across a week, producing curated
markdown reports with top stories, rising topics, and takeaways.
"""

from datetime import datetime, timedelta
from collections import defaultdict


class WeeklyReport:
    """Generates weekly reports from digest archives."""

            def __init__(self, week_start):
                    self.week_start = week_start
                            self.week_end = week_start + timedelta(days=6)
                                    self.stories = []
                                            self.categories = defaultdict(int)
                                                    self.entities = defaultdict(int)

                                                            def add_story(self, headline, summary, category, entities=None):
                                                                    """Record a story for the report."""
                                                                            self.stories.append({
                                                                                        'headline': headline,
                                                                                                    'summary': summary,
                                                                                                                'category': category,
                                                                                                                            'entities': entities or []
                                                                                                                                    })
                                                                                                                                            self.categories[category] += 1
                                                                                                                                                    for e in (entities or []):
                                                                                                                                                                self.entities[e] += 1
                                                                                                                                                                    
                                                                                                                                                                        def render_markdown(self):
                                                                                                                                                                                """Generate markdown-formatted report."""
                                                                                                                                                                                        lines = [
                                                                                                                                                                                                    f"# Weekly AI Report - Week of {self.week_start.strftime('%Y-%m-%d')}",
                                                                                                                                                                                                                f"Period: {self.week_start.strftime('%b %d')} to {self.week_end.strftime('%b %d, %Y')}",
                                                                                                                                                                                                                            f"Total stories: {len(self.stories)}",
                                                                                                                                                                                                                                        ""
                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                if self.stories:
                                                                                                                                                                                                                                                                            lines.append("## Top Stories")
                                                                                                                                                                                                                                                                                        for s in self.stories[:5]:
                                                                                                                                                                                                                                                                                                        lines.append(f"- **{s['headline']}** ({s['category']})")
                                                                                                                                                                                                                                                                                                                        lines.append(f"  {s['summary']}")
                                                                                                                                                                                                                                                                                                                                    lines.append("")
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                    if self.categories:
                                                                                                                                                                                                                                                                                                                                                                lines.append("## By Category")
                                                                                                                                                                                                                                                                                                                                                                            for cat, cnt in sorted(self.categories.items(), key=lambda x: -x[1]):
                                                                                                                                                                                                                                                                                                                                                                                            lines.append(f"- {cat}: {cnt}")
                                                                                                                                                                                                                                                                                                                                                                                                        lines.append("")
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                        if self.entities:
                                                                                                                                                                                                                                                                                                                                                                                                                                    lines.append("## Most Mentioned")
                                                                                                                                                                                                                                                                                                                                                                                                                                                for ent, cnt in sorted(self.entities.items(), key=lambda x: -x[1])[:8]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                lines.append(f"- {ent} ({cnt})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "\n".join(lines)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Demo: create sample weekly report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        report = WeeklyReport(datetime(2026, 8, 4))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                report.add_story(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "GPT-5.6 Luna Pricing Cut 80%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "OpenAI slashes API costs following market pressure.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "products",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["OpenAI", "GPT-5.6"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        report.add_story(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "EU AI Act Enforcement Phase Begins",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Transparency requirements take effect; fines up to 3% turnover.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "policy",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ["EU", "AI Act"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                report.add_story(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Kimi K3 Open Weights Released",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Moonshot AI releases 2.8T parameter sparse MoE model.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "research",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["Moonshot", "Kimi K3"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(report.render_markdown())
